[tox]
envlist = py313
isolated_build = false

[testenv]
setenv =
    GENVM_VERSION = v0.6.0-rc6
deps =
    -r requirements-dev.txt
commands =
    genvm-lint contracts/contract.py
    python -m pytest -q
